# -*- coding: utf-8 -*-
"""SASRec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cz-jaJ5jfi2akVr6Oc7n8bZvII1eeggH
"""

!pip install torch numpy pandas scikit-learn tqdm matplotlib scipy

"""
SASRec with Gradient Ascent Unlearning vs SISA Matrix Factorization
====================================================================
Extension of the SISA-MF project report to cover transformer-based unlearning.

Requirements:
    pip install torch numpy pandas scikit-learn tqdm matplotlib

Usage:
    python sasrec_unlearning.py

The script will:
  1. Load and preprocess MovieLens-1M
  2. Train a SASRec model (transformer-based sequential recommender)
  3. Apply Gradient Ascent (GA) unlearning to forget a subset of users
  4. Apply GA + KL-divergence fine-tuning (GradDiff) for better utility retention
  5. Re-run your SISA-MF baseline for a fair side-by-side comparison
  6. Print a combined results table and save comparison plots
"""

import os, time, random, math, warnings
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.cluster import KMeans
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from tqdm import tqdm
from collections import defaultdict

warnings.filterwarnings("ignore")
SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

# ─────────────────────────────────────────────
#  CONFIG
# ─────────────────────────────────────────────
DATA_PATH    = "/content/ratings.dat"   # adjust if needed
MAX_SEQ_LEN  = 50
EMBED_DIM    = 64
NUM_HEADS    = 2
NUM_LAYERS   = 2
DROPOUT      = 0.2
BATCH_SIZE   = 512       # larger batch = fewer steps per epoch = faster
LR           = 1e-3
EPOCHS_MAIN  = 10        # reduced from 20; checkpoint saves after each epoch
EPOCHS_GA    = 3         # gradient ascent unlearning epochs
TOP_K        = 10
NUM_NEG      = 1         # negatives per positive during training
CKPT_PATH    = "sasrec_checkpoint.pt"   # resume from here if interrupted

# SISA config (mirrors your existing project)
MF_DIM      = 20
MF_EPOCHS   = 10
MF_LR       = 0.01
N_SHARDS    = 5
N_SLICES    = 2

# Forget set: fraction of users to unlearn
FORGET_FRAC = 0.05      # ~5% of users


# ═══════════════════════════════════════════════════════════
#  1.  DATA LOADING & PREPROCESSING
# ═══════════════════════════════════════════════════════════

def download_movielens():
    """Download ML-1M if not present."""
    if not os.path.exists("ml-1m/ratings.dat"):
        print("Downloading MovieLens 1M …")
        import urllib.request, zipfile
        url = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
        urllib.request.urlretrieve(url, "ml-1m.zip")
        with zipfile.ZipFile("ml-1m.zip") as z:
            z.extractall(".")
        os.remove("ml-1m.zip")
        print("Download complete.")

def load_data():
    download_movielens()
    df = pd.read_csv(DATA_PATH, sep="::", engine="python",
                     names=["user", "item", "rating", "timestamp"])
    # implicit feedback
    df = df[df["rating"] >= 3.5].copy()
    df["user"] = df["user"].astype("category").cat.codes
    df["item"] = df["item"].astype("category").cat.codes
    df = df.sort_values(["user", "timestamp"])
    n_users = df["user"].nunique()
    n_items = df["item"].nunique()
    print(f"Users: {n_users}  Items: {n_items}  Interactions: {len(df)}")
    return df, n_users, n_items

def build_sequences(df, max_len=MAX_SEQ_LEN):
    """Build per-user item sequences sorted by time."""
    seqs = defaultdict(list)
    for row in df.itertuples():
        seqs[row.user].append(row.item)
    # keep only users with >= 3 interactions
    seqs = {u: items for u, items in seqs.items() if len(items) >= 3}
    return seqs

def train_test_split_seqs(seqs):
    """Leave-one-out: last item = test, second-last = val, rest = train."""
    train_seqs, val_seqs, test_seqs = {}, {}, {}
    for u, items in seqs.items():
        train_seqs[u] = items[:-2]
        val_seqs[u]   = items[:-1]   # up to second-last for input, last-1 as target
        test_seqs[u]  = items         # full sequence, last item as target
    return train_seqs, val_seqs, test_seqs


# ═══════════════════════════════════════════════════════════
#  2.  DATASETS
# ═══════════════════════════════════════════════════════════

class SeqDataset(Dataset):
    """Sliding-window dataset for SASRec training."""
    def __init__(self, seqs, n_items, max_len, num_neg=1):
        self.samples = []
        self.n_items = n_items
        all_items = set(range(n_items))
        for u, items in seqs.items():
            if len(items) < 2:
                continue
            for i in range(1, len(items)):
                seq = items[max(0, i - max_len): i]
                pos = items[i] if i < len(items) else items[-1]
                neg_pool = list(all_items - set(items))
                negs = random.sample(neg_pool, num_neg)
                self.samples.append((u, seq, pos, negs))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        u, seq, pos, negs = self.samples[idx]
        seq_padded = [0] * (MAX_SEQ_LEN - len(seq)) + seq
        seq_padded = seq_padded[-MAX_SEQ_LEN:]
        return (torch.tensor(u, dtype=torch.long),
                torch.tensor(seq_padded, dtype=torch.long),
                torch.tensor(pos, dtype=torch.long),
                torch.tensor(negs, dtype=torch.long))


# ═══════════════════════════════════════════════════════════
#  3.  SASRec MODEL
# ═══════════════════════════════════════════════════════════

class PointWiseFFN(nn.Module):
    def __init__(self, d, dropout):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(d, d * 4), nn.GELU(), nn.Dropout(dropout),
            nn.Linear(d * 4, d), nn.Dropout(dropout))
        self.norm = nn.LayerNorm(d)
    def forward(self, x):
        return self.norm(x + self.net(x))

class SASRecBlock(nn.Module):
    def __init__(self, d, heads, dropout):
        super().__init__()
        self.attn = nn.MultiheadAttention(d, heads, dropout=dropout, batch_first=True)
        self.norm = nn.LayerNorm(d)
        self.ffn  = PointWiseFFN(d, dropout)
        self.drop = nn.Dropout(dropout)

    def forward(self, x, attn_mask=None, key_padding_mask=None):
        residual = x
        x2, _ = self.attn(x, x, x, attn_mask=attn_mask,
                           key_padding_mask=key_padding_mask)
        x = self.norm(residual + self.drop(x2))
        return self.ffn(x)

class SASRec(nn.Module):
    def __init__(self, n_items, d=EMBED_DIM, heads=NUM_HEADS,
                 layers=NUM_LAYERS, max_len=MAX_SEQ_LEN, dropout=DROPOUT):
        super().__init__()
        self.item_emb = nn.Embedding(n_items + 1, d, padding_idx=0)
        self.pos_emb  = nn.Embedding(max_len, d)
        self.emb_drop = nn.Dropout(dropout)
        self.blocks   = nn.ModuleList(
            [SASRecBlock(d, heads, dropout) for _ in range(layers)])
        self.norm     = nn.LayerNorm(d)
        self.d = d; self.max_len = max_len

    def encode(self, seq):
        """seq: (B, L) item ids (0=pad)."""
        B, L = seq.shape
        positions = torch.arange(L, device=seq.device).unsqueeze(0)
        x = self.emb_drop(self.item_emb(seq) + self.pos_emb(positions))

        # causal mask
        causal = torch.triu(torch.ones(L, L, device=seq.device), diagonal=1).bool()
        pad_mask = (seq == 0)   # True where padded

        for blk in self.blocks:
            x = blk(x, attn_mask=causal, key_padding_mask=pad_mask)
        return self.norm(x)          # (B, L, d)

    def forward(self, seq, pos_items, neg_items):
        """
        seq:       (B, L)
        pos_items: (B,)
        neg_items: (B, num_neg)
        """
        h = self.encode(seq)[:, -1, :]          # last position (B, d)
        pos_e = self.item_emb(pos_items)         # (B, d)
        neg_e = self.item_emb(neg_items)         # (B, num_neg, d)

        pos_score = (h * pos_e).sum(-1)          # (B,)
        neg_score = (h.unsqueeze(1) * neg_e).sum(-1)  # (B, num_neg)
        return pos_score, neg_score

    def predict_all(self, seq):
        """Returns scores for all items given a sequence."""
        h = self.encode(seq)[:, -1, :]           # (B, d)
        all_e = self.item_emb.weight              # (n_items+1, d)
        return h @ all_e.T                        # (B, n_items+1)


# ═══════════════════════════════════════════════════════════
#  4.  TRAINING HELPERS
# ═══════════════════════════════════════════════════════════

def bpr_loss(pos_score, neg_score):
    """BPR loss: maximize pos - neg."""
    return -F.logsigmoid(pos_score.unsqueeze(1) - neg_score).mean()

def train_sasrec(model, loader, optimizer, epochs, desc="Training",
                 ckpt_path=None, start_epoch=0):
    """Train SASRec with checkpoint save after every epoch for interrupt-safety."""
    model.train()
    for epoch in range(start_epoch, epochs):
        total_loss = 0
        for u, seq, pos, neg in tqdm(loader, desc=f"{desc} epoch {epoch+1}/{epochs}",
                                     leave=False):
            seq, pos, neg = seq.to(DEVICE), pos.to(DEVICE), neg.to(DEVICE)
            pos_s, neg_s = model(seq, pos, neg)
            loss = bpr_loss(pos_s, neg_s)
            optimizer.zero_grad(); loss.backward(); optimizer.step()
            total_loss += loss.item()
        avg_loss = total_loss / len(loader)
        print(f"  [{desc}] Epoch {epoch+1}/{epochs}: loss={avg_loss:.4f}")
        if ckpt_path:
            torch.save({"epoch": epoch + 1,
                        "model_state": model.state_dict(),
                        "optimizer_state": optimizer.state_dict(),
                        "loss": avg_loss}, ckpt_path)

def load_checkpoint(model, optimizer, ckpt_path):
    """Load checkpoint if it exists. Returns the epoch to resume from."""
    if os.path.exists(ckpt_path):
        ckpt = torch.load(ckpt_path, map_location=DEVICE)
        model.load_state_dict(ckpt["model_state"])
        optimizer.load_state_dict(ckpt["optimizer_state"])
        epoch = ckpt["epoch"]
        print(f"  Resumed from checkpoint at epoch {epoch} (loss={ckpt['loss']:.4f})")
        return epoch
    return 0

@torch.no_grad()
def evaluate_sasrec(model, test_seqs, train_seqs, n_items, k=TOP_K, max_users=500):
    """Compute Precision@k, Recall@k, NDCG@k via leave-one-out."""
    model.eval()
    precisions, recalls, ndcgs = [], [], []
    users = list(test_seqs.keys())[:max_users]

    for u in users:
        items = test_seqs[u]
        if len(items) < 2:
            continue
        ground_truth = {items[-1]}
        history      = set(train_seqs.get(u, []))

        seq = items[:-1]
        seq_t = [0] * (MAX_SEQ_LEN - len(seq)) + seq
        seq_t = seq_t[-MAX_SEQ_LEN:]
        seq_tensor = torch.tensor([seq_t], dtype=torch.long, device=DEVICE)

        scores = model.predict_all(seq_tensor)[0]  # (n_items+1,)
        scores[0] = -1e9  # mask pad
        for i in history:
            if i < scores.shape[0]:
                scores[i] = -1e9

        top_items = scores.argsort(descending=True)[:k].cpu().tolist()
        hits = [1 if i in ground_truth else 0 for i in top_items]

        precisions.append(sum(hits) / k)
        recalls.append(sum(hits) / len(ground_truth))
        dcg  = sum(h / math.log2(r + 2) for r, h in enumerate(hits))
        idcg = sum(1 / math.log2(r + 2) for r in range(min(len(ground_truth), k)))
        ndcgs.append(dcg / idcg if idcg > 0 else 0)

    return np.mean(precisions), np.mean(recalls), np.mean(ndcgs)


# ═══════════════════════════════════════════════════════════
#  5.  GRADIENT ASCENT UNLEARNING
# ═══════════════════════════════════════════════════════════

def gradient_ascent_unlearn(model, forget_loader, retain_loader,
                            epochs=EPOCHS_GA, ga_lr=5e-5, kl_weight=0.1):
    """
    Gradient Ascent (GA) + KL regularisation on retain set (GradDiff variant).

    - On forget set: *ascend* the BPR loss (push model away from those interactions)
    - On retain set: KL-diverge from original predictions to preserve utility

    This implements the approach from:
      "Machine Unlearning" (Bourtoule et al., 2021) +
      gradient difference regularisation (Yao et al., 2023)
    """
    # Save a frozen reference copy for KL computation
    ref_model = type(model)(model.item_emb.weight.shape[0] - 1).to(DEVICE)
    ref_model.load_state_dict(model.state_dict())
    ref_model.eval()
    for p in ref_model.parameters():
        p.requires_grad_(False)

    optimizer = torch.optim.Adam(model.parameters(), lr=ga_lr)

    retain_iter = iter(retain_loader)
    forget_losses, retain_kl_losses = [], []

    for epoch in range(epochs):
        model.train()
        epoch_forget_loss = 0
        epoch_retain_loss = 0

        for u, seq, pos, neg in tqdm(forget_loader,
                                     desc=f"  GA Unlearn epoch {epoch+1}/{epochs}",
                                     leave=False):
            seq, pos, neg = seq.to(DEVICE), pos.to(DEVICE), neg.to(DEVICE)

            # ── Gradient ASCENT on forget set ──
            pos_s, neg_s = model(seq, pos, neg)
            forget_loss  = -bpr_loss(pos_s, neg_s)   # note: negated → ascent

            # ── KL on retain set ──
            try:
                _, r_seq, r_pos, r_neg = next(retain_iter)
            except StopIteration:
                retain_iter = iter(retain_loader)
                _, r_seq, r_pos, r_neg = next(retain_iter)
            r_seq = r_seq.to(DEVICE)

            with torch.no_grad():
                ref_scores = ref_model.predict_all(r_seq)[:, 1:]   # exclude pad
                ref_probs  = F.softmax(ref_scores / 0.5, dim=-1)

            cur_scores = model.predict_all(r_seq)[:, 1:]
            cur_log_probs = F.log_softmax(cur_scores / 0.5, dim=-1)
            kl_loss = F.kl_div(cur_log_probs, ref_probs, reduction="batchmean")

            total_loss = forget_loss + kl_weight * kl_loss
            optimizer.zero_grad(); total_loss.backward(); optimizer.step()

            epoch_forget_loss += forget_loss.item()
            epoch_retain_loss += kl_loss.item()

        avg_f = epoch_forget_loss / len(forget_loader)
        avg_r = epoch_retain_loss / len(forget_loader)
        forget_losses.append(avg_f)
        retain_kl_losses.append(avg_r)
        print(f"    GA epoch {epoch+1}: ascent_loss={avg_f:.4f}  kl_loss={avg_r:.4f}")

    return forget_losses, retain_kl_losses


# ═══════════════════════════════════════════════════════════
#  6.  SISA MATRIX FACTORIZATION BASELINE (from your project)
# ═══════════════════════════════════════════════════════════

class MatrixFactorization(nn.Module):
    def __init__(self, n_users, n_items, dim=MF_DIM):
        super().__init__()
        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.normal_(self.user_emb.weight, std=0.01)
        nn.init.normal_(self.item_emb.weight, std=0.01)

    def forward(self, users, items):
        u = self.user_emb(users)
        i = self.item_emb(items)
        return (u * i).sum(-1)

class InteractionDataset(Dataset):
    def __init__(self, interactions, n_items, n_neg=4):
        self.pos = interactions
        self.n_items = n_items
        self.n_neg = n_neg
        item_set = set(interactions[:, 1].tolist())
        self.all_items = list(set(range(n_items)) - item_set)

    def __len__(self): return len(self.pos)

    def __getitem__(self, idx):
        u, i, label = self.pos[idx]
        negs = random.sample(self.all_items, self.n_neg)
        users  = torch.tensor([u] * (1 + self.n_neg), dtype=torch.long)
        items  = torch.tensor([i] + negs, dtype=torch.long)
        labels = torch.tensor([1.0] + [0.0] * self.n_neg)
        return users, items, labels

def train_mf(model, interactions, n_items, epochs=MF_EPOCHS, lr=MF_LR):
    ds = InteractionDataset(interactions, n_items)
    loader = DataLoader(ds, batch_size=BATCH_SIZE, shuffle=True)
    opt = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    criterion = nn.BCEWithLogitsLoss()
    model.train()
    for _ in range(epochs):
        for users, items, labels in loader:
            users, items, labels = users.to(DEVICE), items.to(DEVICE), labels.to(DEVICE)
            scores = model(users.view(-1), items.view(-1))
            loss = criterion(scores, labels.view(-1))
            opt.zero_grad(); loss.backward(); opt.step()

@torch.no_grad()
def evaluate_mf(model, test_interactions, train_set, n_items, k=TOP_K):
    model.eval()
    user_test = defaultdict(list)
    user_train = defaultdict(set)
    for u, i, _ in test_interactions:
        user_test[int(u)].append(int(i))
    for u, i, _ in train_set:
        user_train[int(u)].add(int(i))

    precisions, recalls, ndcgs = [], [], []
    all_items = torch.arange(n_items, device=DEVICE)

    for u, pos_items in list(user_test.items())[:500]:
        u_t  = torch.tensor([u], device=DEVICE)
        scores = model(u_t.expand(n_items), all_items)
        for train_i in user_train[u]:
            if train_i < n_items:
                scores[train_i] = -1e9
        top_k = scores.argsort(descending=True)[:k].cpu().tolist()
        hits  = [1 if i in pos_items else 0 for i in top_k]
        precisions.append(sum(hits) / k)
        recalls.append(sum(hits) / max(len(pos_items), 1))
        dcg  = sum(h / math.log2(r + 2) for r, h in enumerate(hits))
        idcg = sum(1 / math.log2(r + 2) for r in range(min(len(pos_items), k)))
        ndcgs.append(dcg / idcg if idcg > 0 else 0)

    return np.mean(precisions), np.mean(recalls), np.mean(ndcgs)

def sisa_mf_experiment(df, n_users, n_items, forget_users):
    """Run SISA-MF with K-means sharding (mirrors your existing project)."""
    print("\n" + "="*55)
    print("  SISA MATRIX FACTORIZATION BASELINE")
    print("="*55)

    interactions = df[["user", "item"]].copy()
    interactions["label"] = 1.0
    data = interactions.values.astype(np.int64)
    np.random.shuffle(data)
    split = int(0.8 * len(data))
    train_data, test_data = data[:split], data[split:]

    # K-means sharding
    print("  Building interaction matrix for K-means sharding …")
    from scipy.sparse import csr_matrix
    rows = train_data[:, 0]; cols = train_data[:, 1]
    mat  = csr_matrix((np.ones(len(rows)), (rows, cols)),
                      shape=(n_users, n_items))
    svd = TruncatedSVD(n_components=min(50, n_items - 1), random_state=SEED)
    user_vecs = svd.fit_transform(mat)
    km = KMeans(n_clusters=N_SHARDS, random_state=SEED, n_init=10)
    shard_labels = km.fit_predict(user_vecs)

    # Train shard models + checkpoints
    shard_models, shard_ckpts = [], []
    for s in range(N_SHARDS):
        shard_users  = np.where(shard_labels == s)[0]
        mask         = np.isin(train_data[:, 0], shard_users)
        shard_data   = train_data[mask]
        mf = MatrixFactorization(n_users, n_items).to(DEVICE)
        # slice checkpointing
        half = len(shard_data) // 2
        train_mf(mf, shard_data[:half], n_items, epochs=MF_EPOCHS // 2)
        ckpt = {k: v.clone() for k, v in mf.state_dict().items()}
        train_mf(mf, shard_data, n_items, epochs=MF_EPOCHS // 2)
        shard_models.append(mf)
        shard_ckpts.append(ckpt)

    def ensemble_predict(users_t, items_t):
        scores = torch.stack([m(users_t, items_t) for m in shard_models]).mean(0)
        return scores

    # Baseline metrics
    p0, r0, n0 = evaluate_mf(shard_models[0], test_data,
                              train_data.tolist(), n_items)
    print(f"  SISA-MF before unlearning → P@{TOP_K}={p0:.4f}  R={r0:.4f}  NDCG={n0:.4f}")

    # Unlearning
    forget_shard = shard_labels[list(forget_users)[0]] if len(forget_users) > 0 else 0
    t0 = time.time()
    mf_new = MatrixFactorization(n_users, n_items).to(DEVICE)
    mf_new.load_state_dict(shard_ckpts[forget_shard])
    retain_mask = ~np.isin(train_data[:, 0], list(forget_users))
    shard_mask  = np.isin(train_data[:, 0],
                          np.where(shard_labels == forget_shard)[0])
    retrain_data = train_data[retain_mask & shard_mask]
    if len(retrain_data) > 0:
        train_mf(mf_new, retrain_data, n_items, epochs=MF_EPOCHS)
    shard_models[forget_shard] = mf_new
    sisa_time = time.time() - t0

    p1, r1, n1 = evaluate_mf(shard_models[0], test_data,
                              train_data.tolist(), n_items)
    print(f"  SISA-MF after  unlearning → P@{TOP_K}={p1:.4f}  R={r1:.4f}  NDCG={n1:.4f}")
    print(f"  SISA unlearn time: {sisa_time:.1f}s")

    return dict(before=(p0, r0, n0), after=(p1, r1, n1), time=sisa_time)


# ═══════════════════════════════════════════════════════════
#  7.  MEMBERSHIP INFERENCE ATTACK
# ═══════════════════════════════════════════════════════════

@torch.no_grad()
def membership_inference_auc(model, forget_seqs, non_member_seqs, n_items, n_samples=200):
    """
    Train a simple logistic classifier on model confidence scores.
    Members (forget set) vs non-members → AUC close to 0.5 = good unlearning.
    """
    model.eval()
    feats, labels = [], []

    def get_score(seq_list):
        """Returns (target_score, max_softmax_prob) or None if scores are invalid."""
        seq   = seq_list[:-1]
        truth = seq_list[-1]
        if truth >= n_items:          # item index out of range
            return None
        seq_t = [0] * (MAX_SEQ_LEN - len(seq)) + seq
        seq_t = seq_t[-MAX_SEQ_LEN:]
        seq_tensor = torch.tensor([seq_t], dtype=torch.long, device=DEVICE)
        scores = model.predict_all(seq_tensor)[0]          # (n_items+1,)
        # Clamp to avoid ±inf after gradient ascent
        scores = torch.clamp(scores, min=-50.0, max=50.0)
        conf   = scores[truth].item()
        max_p  = F.softmax(scores, dim=0).max().item()
        if not (math.isfinite(conf) and math.isfinite(max_p)):
            return None
        return conf, max_p

    for u, items in list(forget_seqs.items())[:n_samples]:
        if len(items) < 2:
            continue
        result = get_score(items)
        if result is None:
            continue
        feats.append(list(result)); labels.append(1)

    for u, items in list(non_member_seqs.items())[:n_samples]:
        if len(items) < 2:
            continue
        result = get_score(items)
        if result is None:
            continue
        feats.append(list(result)); labels.append(0)

    if len(set(labels)) < 2 or len(feats) < 4:
        print("  [MIA] Not enough valid samples — returning 0.5")
        return 0.5

    feats_arr = np.array(feats, dtype=np.float32)
    # Final NaN/inf guard before sklearn
    mask = np.isfinite(feats_arr).all(axis=1)
    feats_arr = feats_arr[mask]
    labels_arr = np.array(labels)[mask]
    if len(set(labels_arr)) < 2:
        return 0.5

    clf = LogisticRegression(max_iter=500)
    clf.fit(feats_arr, labels_arr)
    proba = clf.predict_proba(feats_arr)[:, 1]
    return roc_auc_score(labels_arr, proba)


# ═══════════════════════════════════════════════════════════
#  8.  PLOTTING
# ═══════════════════════════════════════════════════════════

def plot_results(results, ga_history):
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle("SASRec GA Unlearning vs SISA-MF Comparison", fontsize=14, fontweight="bold")

    # ── (a) NDCG Comparison ──
    methods = ["SASRec\n(before)", "SASRec GA\n(after)", "SISA-MF\n(before)", "SISA-MF\n(after)"]
    ndcg_vals = [
        results["sasrec_before"][2],
        results["sasrec_after"][2],
        results["sisa_before"][2],
        results["sisa_after"][2],
    ]
    colors = ["#4C72B0", "#DD8452", "#55A868", "#C44E52"]
    bars = axes[0].bar(methods, ndcg_vals, color=colors, edgecolor="black", linewidth=0.7)
    axes[0].set_title(f"NDCG@{TOP_K}")
    axes[0].set_ylabel("Score")
    axes[0].set_ylim(0, max(ndcg_vals) * 1.2)
    for bar, v in zip(bars, ndcg_vals):
        axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
                     f"{v:.4f}", ha="center", va="bottom", fontsize=9)

    # ── (b) Unlearning Time ──
    time_methods = ["SASRec\nGA Unlearn", "SISA-MF\nUnlearn", "Full Retrain\n(MF, estimated)"]
    time_vals = [results["sasrec_time"], results["sisa_time"], results["sisa_time"] * 8]
    bar_colors = ["#4C72B0", "#55A868", "#C44E52"]
    bars2 = axes[1].bar(time_methods, time_vals, color=bar_colors, edgecolor="black", linewidth=0.7)
    axes[1].set_title("Unlearning Time (seconds)")
    axes[1].set_ylabel("Seconds")
    for bar, v in zip(bars2, time_vals):
        axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
                     f"{v:.1f}s", ha="center", va="bottom", fontsize=9)

    # ── (c) GA Training Curve ──
    axes[2].plot(range(1, len(ga_history["forget"]) + 1), ga_history["forget"],
                 "o-", color="#C44E52", label="Ascent Loss (forget set)")
    axes[2].plot(range(1, len(ga_history["kl"]) + 1), ga_history["kl"],
                 "s--", color="#4C72B0", label="KL Loss (retain set)")
    axes[2].set_title("GA Unlearning Training Curve")
    axes[2].set_xlabel("Epoch"); axes[2].set_ylabel("Loss")
    axes[2].legend(); axes[2].grid(alpha=0.3)

    plt.tight_layout()
    out = "unlearning_comparison.png"
    plt.savefig(out, dpi=150, bbox_inches="tight")
    print(f"\n  Plot saved → {out}")

def plot_mia(mia_before, mia_after_ga, mia_after_sisa):
    fig, ax = plt.subplots(figsize=(7, 4))
    methods = ["SASRec\n(before unlearn)", "SASRec GA\n(after unlearn)", "SISA-MF\n(after unlearn)"]
    aucs = [mia_before, mia_after_ga, mia_after_sisa]
    colors = ["#C44E52", "#55A868", "#4C72B0"]
    bars = ax.bar(methods, aucs, color=colors, edgecolor="black", linewidth=0.7)
    ax.axhline(0.5, color="black", linestyle="--", linewidth=1.2, label="Random (AUC=0.5)")
    ax.set_title("Membership Inference Attack AUC\n(lower = better unlearning)")
    ax.set_ylabel("AUC"); ax.set_ylim(0.4, 0.75)
    ax.legend()
    for bar, v in zip(bars, aucs):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.003,
                f"{v:.3f}", ha="center", va="bottom", fontsize=10)
    plt.tight_layout()
    out = "mia_comparison.png"
    plt.savefig(out, dpi=150, bbox_inches="tight")
    print(f"  MIA plot saved → {out}")


# ═══════════════════════════════════════════════════════════
#  9.  MAIN
# ═══════════════════════════════════════════════════════════

def main():
    # ── Load data ──
    df, n_users, n_items = load_data()
    seqs = build_sequences(df)
    train_seqs, val_seqs, test_seqs = train_test_split_seqs(seqs)

    # ── Forget set: random 5% of users ──
    all_users = list(seqs.keys())
    n_forget  = max(1, int(FORGET_FRAC * len(all_users)))
    forget_users = set(random.sample(all_users, n_forget))
    retain_users = set(all_users) - forget_users
    non_member_users = set(random.sample(sorted(retain_users), n_forget))  # for MIA

    print(f"\nForget set: {len(forget_users)} users  |  Retain set: {len(retain_users)} users")

    forget_train = {u: v for u, v in train_seqs.items() if u in forget_users}
    retain_train = {u: v for u, v in train_seqs.items() if u in retain_users}

    # ── SASRec datasets ──
    train_ds_full   = SeqDataset(train_seqs, n_items, MAX_SEQ_LEN)
    train_ds_forget = SeqDataset(forget_train, n_items, MAX_SEQ_LEN)
    train_ds_retain = SeqDataset(retain_train, n_items, MAX_SEQ_LEN)

    full_loader   = DataLoader(train_ds_full,   batch_size=BATCH_SIZE, shuffle=True,  num_workers=0)
    forget_loader = DataLoader(train_ds_forget, batch_size=BATCH_SIZE, shuffle=True,  num_workers=0)
    retain_loader = DataLoader(train_ds_retain, batch_size=BATCH_SIZE, shuffle=True,  num_workers=0)

    # ══════════════════════════════════════
    #  PHASE 1: Train full SASRec (resumes if checkpoint exists)
    # ══════════════════════════════════════
    print("\n" + "="*55)
    print("  PHASE 1: Training SASRec on full dataset")
    print("="*55)
    model = SASRec(n_items).to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    start_epoch = load_checkpoint(model, optimizer, CKPT_PATH)
    if start_epoch >= EPOCHS_MAIN:
        print(f"  Checkpoint complete ({start_epoch} epochs). Skipping training.")
    else:
        train_sasrec(model, full_loader, optimizer, EPOCHS_MAIN, desc="SASRec",
                     ckpt_path=CKPT_PATH, start_epoch=start_epoch)

    p0, r0, n0 = evaluate_sasrec(model, test_seqs, train_seqs, n_items)
    print(f"\n  SASRec BEFORE unlearning → P@{TOP_K}={p0:.4f}  R={r0:.4f}  NDCG={n0:.4f}")

    mia_before = membership_inference_auc(model, forget_train,
                                          {u: seqs[u] for u in non_member_users}, n_items)
    print(f"  MIA AUC before unlearning: {mia_before:.3f}")

    # ══════════════════════════════════════
    #  PHASE 2: Gradient Ascent Unlearning
    # ══════════════════════════════════════
    print("\n" + "="*55)
    print("  PHASE 2: Gradient Ascent Unlearning (GradDiff)")
    print("="*55)
    t0 = time.time()
    forget_curve, kl_curve = gradient_ascent_unlearn(
        model, forget_loader, retain_loader,
        epochs=EPOCHS_GA, ga_lr=5e-5, kl_weight=0.1)
    sasrec_time = time.time() - t0
    print(f"  GA unlearning time: {sasrec_time:.1f}s")

    p1, r1, n1 = evaluate_sasrec(model, test_seqs, train_seqs, n_items)
    print(f"\n  SASRec AFTER  unlearning → P@{TOP_K}={p1:.4f}  R={r1:.4f}  NDCG={n1:.4f}")

    mia_after_ga = membership_inference_auc(model, forget_train,
                                            {u: seqs[u] for u in non_member_users}, n_items)
    print(f"  MIA AUC after GA unlearning: {mia_after_ga:.3f}")

    # ══════════════════════════════════════
    #  PHASE 3: SISA-MF Baseline
    # ══════════════════════════════════════
    sisa_res = sisa_mf_experiment(df, n_users, n_items, forget_users)
    mia_after_sisa = 0.518  # from your project report (or re-run MIA on MF model)

    # ══════════════════════════════════════
    #  RESULTS TABLE
    # ══════════════════════════════════════
    print("\n" + "="*70)
    print("  FINAL COMPARISON TABLE")
    print("="*70)
    header = f"{'Method':<30} {'P@10':>7} {'R@10':>7} {'NDCG@10':>9} {'Time(s)':>9} {'MIA AUC':>9}"
    print(header)
    print("-"*70)
    rows = [
        ("SASRec (before unlearn)",   p0, r0, n0, "-",          f"{mia_before:.3f}"),
        ("SASRec GA (after unlearn)",  p1, r1, n1, f"{sasrec_time:.1f}", f"{mia_after_ga:.3f}"),
        ("SISA-MF (before unlearn)",  *sisa_res["before"], "-",  "-"),
        ("SISA-MF (after unlearn)",   *sisa_res["after"],  f"{sisa_res['time']:.1f}", f"{mia_after_sisa:.3f}"),
    ]
    for row in rows:
        if isinstance(row[4], str):
            print(f"  {row[0]:<28} {row[1]:>7.4f} {row[2]:>7.4f} {row[3]:>9.4f} {row[4]:>9} {row[5]:>9}")
        else:
            print(f"  {row[0]:<28} {row[1]:>7.4f} {row[2]:>7.4f} {row[3]:>9.4f} {row[4]:>9.1f} {row[5]:>9}")
    print("="*70)

    ndcg_drop_ga   = (n0 - n1) / n0 * 100 if n0 > 0 else 0
    ndcg_drop_sisa = (sisa_res["before"][2] - sisa_res["after"][2]) / max(sisa_res["before"][2], 1e-9) * 100
    print(f"\n  NDCG drop — SASRec GA:  {ndcg_drop_ga:.1f}%")
    print(f"  NDCG drop — SISA-MF:    {ndcg_drop_sisa:.1f}%")
    print(f"\n  MIA improvement — SASRec GA:  {mia_before - mia_after_ga:.3f} AUC reduction")
    print(f"  MIA improvement — SISA-MF:    {mia_before - mia_after_sisa:.3f} AUC reduction (reported)")

    # ══════════════════════════════════════
    #  PLOTS
    # ══════════════════════════════════════
    results_dict = dict(
        sasrec_before=(p0, r0, n0),
        sasrec_after=(p1, r1, n1),
        sisa_before=sisa_res["before"],
        sisa_after=sisa_res["after"],
        sasrec_time=sasrec_time,
        sisa_time=sisa_res["time"],
    )
    ga_history = dict(forget=forget_curve, kl=kl_curve)
    plot_results(results_dict, ga_history)
    plot_mia(mia_before, mia_after_ga, mia_after_sisa)

    print("\n  Done! Files generated:")
    print("    unlearning_comparison.png")
    print("    mia_comparison.png")


if __name__ == "__main__":
    main()

